In [1]:
### L5 Numerical Linear Algebra 1
'''
- Manipulation of matrices and matrix equations in Python
- Reminder on properties of matrices (from MM1): determinants, singularity etc
- Algorithms for the solution of linear systems
- Gaussian elimination, including back substitution
'''

# Matrixes (determinant, singularity)
# Direct solution methods
    # Glaussian Elimination (and back substitution)
    # Triangle method, back substitution
    # reverse triangle (for diagonal identity matrix), partial pivot

import numpy as np
import scipy.linalg as sl

In [2]:
### Matrixes recap
# real numbers, n = m (square matrixes)
    # more rows (over constrained) --> redundant or no solution
    # less rows (under constrained) --> too many variables

# NumPy array = 1D column vectors --> one column down
# Transpose --> every row is now a column
# Inverse --> multipy by the matrix = unit matrix
    # NOT invertible if determinant = 0
    # dot at the end eg 4. --> changes int to float

In [3]:
## Ex 5.1 solve a simple linear system

A = np.array([[2., 3.], [1., -4.]])
B = np.array([7, 3])

"checks whether an inverse is possible"
assert sl.det(A) != 0, "determinant of the matrix = 0 --> no inverse!!"

"this solves the matrix eqn"
x = sl.inv(A) @ B

print(x)


# Compare to scipy
print(sl.solve(A, B))
print("Check it against the solution we calculated by hand earlier: ", 37./11., 1./11.)

# Check using numpy.allclose:
" checks if two arrays are the same (to round-off error"
print(np.allclose(np.array([37./11., 1./11.]), sl.inv(A) @ B))

[3.36363636 0.09090909]
[3.36363636 0.09090909]
Check it against the solution we calculated by hand earlier:  3.3636363636363638 0.09090909090909091
True


In [4]:
# Slicing random array
A = np.array([[10., 2., 1.],
                [6., 5., 4.],
                [1., 4., 7.]])
print(A)

" extract a single entry, first row, second column (= 2)"
print(A[0,1])

" extract the first row"
print(A[0,:])

" extract the last row"
print(A[-1,:])

" extract the second column"
print(A[:,1])

" extract a 2x2 sub-matrix"
print(A[1:3,1:3])

" replace the third column of A"
A[:,2] = np.array([99.,98.,97.])
print(A)

[[10.  2.  1.]
 [ 6.  5.  4.]
 [ 1.  4.  7.]]
2.0
[10.  2.  1.]
[1. 4. 7.]
[2. 5. 4.]
[[5. 4.]
 [4. 7.]]
[[10.  2. 99.]
 [ 6.  5. 98.]
 [ 1.  4. 97.]]


In [7]:
## Ex 5.3 checking Gaussian elimination of a 3x3 matrix

# Can do the following operations without changing corrosponding sol:
    # Exchange 2 rows (partial pivoting)
    # Multipy a row by a non-zero constant (Eq(i) <-- lamb x Eq(i))
    # Subtracting a (non-zero) multiple of one row with another (Eq(i) <-- Eq(i)) - lamba x Eq(j)

# Upper-triangular matrix --> all entries below diagonal are zero
# Eqn/ row being subtracted --> the pivot

A = np.array([[2., 3., -4.],
                [6., 8., 2.],
                [4., 8., -6.]])

b = np.array([5., 3., 19.])

x = sl.inv(A) @ b

print(x)

[-6.   5.  -0.5]


In [ ]:
### Gaussian elimination upper triangle 
# bk is unaffected as only sub back to bi
# Akk can't be close to zero (s = A[i, k] / A[k, k]) --> partial pivoting